- name: Proxmox // Clone VM Template // kube-cluster
  community.proxmox.proxmox_kvm:
    api_user: root@pam
    api_password: Dev0ps2025
    api_host: pve.lan
    clone: ubuntu-2204-template
    vmid: 999
    newid: "{{ id }}"
    name: "{{ inventory_hostname }}"
    node: pve
    storage: local-lvm
    format: qcow2
    timeout: 1000
  delegate_to: localhost
  throttle: 1

- name: Proxmox // Network // kube-cluster
  community.proxmox.proxmox_kvm:
    api_user: root@pam
    api_password: Dev0ps2025
    api_host: pve.lan
    name: "{{ inventory_hostname }}"
    node: pve
    ipconfig:
      ipconfig0: 'ip={{ ip }},gw=192.168.1.1'
    update: true
  delegate_to: localhost

- name: Proxmox // Start VM // kube-cluster
  community.proxmox.proxmox_kvm:
    api_user: root@pam
    api_password: Dev0ps2025
    api_host: pve.lan
    name: "{{ inventory_hostname }}"
    node: pve
    state: started
  delegate_to: localhost
  throttle: 1

- name: Ansible // Wait for kube-cluster to be reachable
  ansible.builtin.wait_for:
    host: "{{ inventory_hostname }}"
    port: 22
    delay: 240
    sleep: 10
    timeout: 500
    state: started
  delegate_to: localhost
